feat: add ability to set declination of phase center
rasg-affiliates/21cmSense pull request #146
Opened 2024-10-29 09:19 UTC by steven-murray

Adds the ability to set the declination of the phase center of the observation, and adjust the apparent UVWs accordingly.

2024-10-31 09:41 UTC, DanielaBreitman approved these changes
Looks good to me.

2024-11-04 07:25 UTC, telegraphic commented
Thanks @steven-murray, this looks like a great addition. 

Summarizing to check I understand the changes:
* The UVWs are computed using the `uvutils.phasing.calc_uvw` function from pyuvdata. This of course already has support for non-zenith phase centers.
* The main change is in `_utils.py`, to add a `phase_center_dec` argument to `phase_past_zenith` allow off-zenith phasing.
* The `phase_past_zenith()` is called by `Observatory.projected_baselines()`, so this needs a `phase_center_dec` argument added too.
* Similarly `phase_center_dec` is  added to `Observation`
* When UVW coordinates are calculated, they will be calculated using the RA/DEC of the phase center, which no longer needs to be zenith. 

The new code does indeed change UV bins:

![image](https://github.com/user-attachments/assets/24c35795-ab12-435d-9e6c-55d522d32d5a)

2024-11-04 07:37 UTC, telegraphic commented
(thinking more about it: I didn't change the beam, and SEFD will increase for off-zenith pointings with an aperture array. I guess those effects are not accounted for in my simple example?)

2024-11-04 10:43 UTC, steven-murray commented
@telegraphic thanks for the review!

So, yes your outline is correct. I have not touched the beam/SEFD in this PR -- though perhaps it's necessary to obtain reasonable results. Currently we don't have the infrastructure to be able to have a beam whose projected area changes over the course of an observation, however we could at least change the area to be consistent with the projected area when the phase center is as close to the zenith as possible? 

I

2024-11-04 13:28 UTC, jpober commented
Yeah, we've kind of always neglected the primary beam response when considering tracked observations.  The argument was always that you've either got a steerable dish (and hence the SEFD can stay constant as you follow the field) or you've got an aperture array where you're beamforming (in which case there is an increase of the SEFD off-zenith, but it's small since it's set by the primary beam of a single dipole, not the station/tile, and those are very wide).  Realistically you would want to account for it, but I think it's a pretty big change to the inner workings of 21cmSense to make it work.

2024-12-16 14:48 UTC, steven-murray commented
@telegraphic are you happy for this PR to be merged? We could attempt to implement a changing beam area as a function of pointing, but I'm not sure how much it will affect results in realistic cases (where you're not pointing at the horizon...), and it would be a reasonably involved bit of work.

2024-12-26 04:36 UTC, telegraphic commented
Hi @steven-murray, yes happy for this to be merged. As @jpober mentioned, for a steerable dish the SEFD would not change, so it seems reasonable to leave to the user to implement any change in beam characteristics by subclassing `PrimaryBeam`.

FYI, I have used this branch for the SKA-Low EoR sensitivity calculator prototype @ https://github.com/ska-sci-ops/ska-ost-eor-senscalc

2025-01-06 14:16 UTC, DanielaBreitman commented
@jpober we're missing your review. If you're also happy with the changes, we can merge it after your approval. Thanks.

2025-01-06 21:13 UTC, jpober commented
Sorry, didn't realize I was blocking it.  I'll try to have a look tomorrow!

2025-01-07 14:10 UTC, jpober requested changes
One comment but everything else looks great.

2025-01-07 14:10 UTC, jpober commented on src/py21cmsense/_utils.py
> +        zenith_coord = SkyCoord(
For pedagogical clarity, maybe we should rename zenith_coord?  If we're now able to set it to something other than zenith that seems like a bad variable name.

2025-01-08 16:00 UTC, DanielaBreitman commented on src/py21cmsense/_utils.py
> +        zenith_coord = SkyCoord(
how about phase_center_coord?

2025-01-08 16:14 UTC, jpober commented on src/py21cmsense/_utils.py
> +        zenith_coord = SkyCoord(
That sounds good!

2025-01-09 09:25 UTC, merged